eureka:
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/
    register-with-eureka:
        value: true
    fetch-registry:
        value: true
    instance:
        hostname: localhost
spring:
  application:
    name: API_GATEWAY
  cloud:
    gateway:
      routes:

         - id: ProductService
           uri: ${service.product.uri}
           predicates:
             - Path=/api/v1/products/**
           filters:
             - AuthenticationFilter

         - id: OrderService
           uri: ${service.order.uri}
           predicates:
             - Path=/api/v1/orders/**
           filters:
             - AuthenticationFilter

         - id: SalesService
           uri: ${service.sales.uri}
           predicates:
             - Path=/api/v1/sales/**
           filters:
             - AuthenticationFilter

         - id: UserService
           uri: ${service.user.uri}
           predicates:
             - Path=/api/v1/users/**
           filters:
             - AuthenticationFilter

         - id: SupplierService
           uri: ${service.supplier.uri}
           predicates:
             - Path=/api/v1/suppliers/**
           filters:
             AuthenticationFilter
         - id: LoginService
           uri: ${service.login.uri}
           predicates:
             - Path=/api/v1/login/**
           filters:
             - AuthenticationFilter



